### ISSUE TITLE
save log into file.txt

### ISSUE THREAD

**Issue by cesarin3134** [Ritzlgrmft/ionic-logging-service#10]
Is possible to save the logs into a file txt ? 
Thanks

**Comment by Ritzlgrmft** [comment]
Out-of-the-box: no

But you can implement your own Appender, which writes a file. 
For an example, have a look at local-storage-appender.model.ts. The real implementation is in the append method.
For writing the file, you could use cordova-plugin-file.

In you need more support, just let me know. However it will need some time...

**Comment by radulung** [comment]
Hi @Ritzlgrmft 
I tried to implement a file appender for your library, but I have a problem: I write fast more logs and it seams that the cordova File plugin doesn't write the entire text from the first log because it has to start the second one.
So I have something like:
`[21:29:16:631] - [21:29:1[21:29:16:787] - [LOAD_ENDPOINT_CONFIGURATIONS_SUCCESS]`

I hoped that the log4javascript has a queue behind and will call the appender only when the previous operation has finished.
Did you create meanwhile something similar or do you have any suggestion for this issue?

**Comment by Ritzlgrmft** [comment]
In general, log4javascript calls the appender in a synchronous way. However, since the writing to the file itself is an asynchronous operation, you have to implement the queue by yourself.

**Comment by agreeff** [comment]
@radulung any chance you might be able to share an example of how you implemented that file appender..? I've been trying to do that myself most of the day, but I'm not winning.

I'm also working with an app that logs data **fast** (a few hundred lines per second at times), so I created a log queue handler for a different "logging system" (aka: a hack) that now needs to be replaced.. If you can help me work out how to implement a custom appender, then I could adapt it with my file writing logic, and then share that logic with you (of course).

**Comment by radulung** [comment]
Hi Andre, I don't know why I don't see your comment on GitHub, but I am writing you form the email, hope it works.
Meanwhile I also implemented a queue so my problem was fixed. I attach you here some code from my service, hope you will find it usefull:
This is the Appender:import { Injectable } from '@angular/core';import * as log4javascript from 'log4javascript';import { LogFileWriterService } from './log-file-writer.service';
@Injectable()export class LoggingFileAppender extends log4javascript.Appender {  public constructor(private logFileWriterService: LogFileWriterService) {    super();  }
  public append(loggingEvent: log4javascript.LoggingEvent): void {    const layout = this.getLayout();    const message = layout.format(loggingEvent);
    this.logFileWriterService.addLogInQueue(message);  }}

And this is the logging service:import { Injectable } from '@angular/core';import * as log4javascript from 'log4javascript';import { LoggingFileAppender } from './logging-file.appender';
@Injectable()export class LoggingService {  private logger: log4javascript.Logger;
  constructor(private logginFileAppander: LoggingFileAppender) {}
  public initialize(): void {    log4javascript.logLog.setQuietMode(true);
    // configure appender    this.logger = log4javascript.getRootLogger();    this.logger.setLevel(log4javascript.Level.ALL);
    this.logginFileAppander.setLayout(new log4javascript.PatternLayout('%d{HH:mm:ss,SSS} %-5p - %m%n'));    this.logginFileAppander.setThreshold(log4javascript.Level.ALL);    this.logger.addAppender(this.logginFileAppander);  }
  public getLogLevel(): log4javascript.Level {    return this.logger.getLevel();  }
  public setLogLevel(level: log4javascript.Level): void {    this.logger.setLevel(level);  }
  public trace(information: string): void {    if (this.logger.isTraceEnabled()) {      this.logger.trace(information);    }  }
  public debug(information: string): void {    if (this.logger.isDebugEnabled()) {      this.logger.debug(information);    }  }
  public info(information: string): void {    if (this.logger.isInfoEnabled()) {      this.logger.info(information);    }  }
  public error(error: string): void {    if (this.logger.isErrorEnabled()) {      this.logger.error(error);    }  }}


You can see here that I will use the Logging service to log things. This logging service is linked with an appender. And the appender will call another service responsible to put the logs in a queue and to write the queue in a file (using the LogFileWriterService)
The LogFileWriterService depends on your implementation, in my case I keep the state of the writer (busy or not) and when I add a new log, if it is NOT BUSY I am trying to write the logs from the queue in a file. If it is busy I just add the log in the queue. When the service write a log from the queue in the file, it will remove it from the queue and it will try to get the next message. If the queue is empty it will become NOT BUSY.
Hope this is helpful for you
    On Wednesday, January 27, 2021, 4:16:51 PM GMT+2, Andre Greeff <notifications@github.com> wrote:  
 
 


@radulung any chance you might be able to share an example of how you implemented that file appender..? I've been trying to do that myself most of the day, but I'm not winning.

I'm also working with an app that logs data fast (a few hundred lines per second at times), so I created a log queue handler for a different "logging system" (aka: a hack) that now needs to be replaced.. If you can help me work out how to implement a custom appender, then I could adapt it with my file writing logic, and then share that logic with you (of course).

**Comment by agreeff** [comment]
Thanks @radulung, I deleted my comment shortly after posting because I ended up ditching this idea and instead extending what I've already made myself. I keep expecting this to be more complicated than it actually is, so I will definitely dig into it again in the near future..

The tricky part for me, is that the project I'm working with is tied to Ionic 3.. Digging through `ionic-logging-service`'s `README` from previoud tags, and eventually following the `ionic-logging-sample` repo link, takes me to a project with **no appenders configured** (hence my initial confusion). I did manage to work out how to correctly attach appenders a bit later, but I had to stop just before getting to the point of creating my own.

Glad to hear you got your side sorted, so thanks again for the reply, really appreciate it. 👍🏼
