### ISSUE TITLE
BrowserConsoleAppender: always log line number?

### ISSUE THREAD

**Issue by lkstnr** [Ritzlgrmft/ionic-logging-service#17]
Is it not possible to always automatically log the line number or am I missing something?

**Comment by Ritzlgrmft** [comment]
`ionic-logging-service` does not support line numbers out-of-the-box, since the underlying `log4javascript` does not provide them. Moreover, I am not convinced if they are useful, when you are using minimised or tree-shaken files in production. 

Anyway, if you need the line numbers, you could use a custom field in the layout. An example how to achieve this, you can find here: https://stackoverflow.com/a/28150218/2686136.
Be aware, this solution is working only in Firefox. For Chrome, you can find something here: https://gist.github.com/leoroos/3441763#file-log4javascript_uncompressed-js-L24.
