### ISSUE TITLE
How to: Is it possible to append to modal viewer component, localStorageAppender messages ?

### ISSUE THREAD

**Issue by cbleu** [Ritzlgrmft/ionic-logging-service#25]
Hi,
Is it possible to have in the modal viewer component present in the npm package, messages saved from previous sessions to the local storage ?

I need that to have multi session logging in the same place over the time.

thanks a lot for your advices and for that wonderful package ! great.

regards,
cesar

**Comment by Ritzlgrmft** [comment]
I am working on a feature to pass some localStorageKeys into the viewer component. If set, the logs get loaded from localStorage instead of memory.

@cbleu I hope this is what you wished?

**Comment by Ritzlgrmft** [comment]
I added a new property `localStorageKeys` to the viewer component. If it is set, the messages are read from local storage instead of memory.
For the modal, you pass it as an additional parameter, see `openModal()` in [home.page.ts](https://github.com/Ritzlgrmft/ionic-logging-service/blob/master/projects/ionic-logging-viewer-app/src/app/home/home.page.ts).
