### ISSUE TITLE
Configure ajax extender

### ISSUE THREAD

**Issue by ChristophRettinger** [Ritzlgrmft/ionic-logging-service#6]
Hi,

thanks for the plugin, its working nicely. I was just trying the ajaxAppender and I succeeded sending the log data to my service.

- Is there a way to enable/disable the ajaxAppender in code, as I want to enable this feature only when the users checks a checkmark
- Can i add a special information to each log statement (sent via ajaxAppender) so that I can identify the device? If multiple apps run at the same time I do not know which log statements go together
- It would be useful to have a timing feature as followed: Batch log statements until _either_ the batch size is exceeded _or_ a timeout threshold is exceeded. If I use batching right now and the app creates an error it is not sent as the batch threashold is not exceeded yet.

regards

**Comment by Ritzlgrmft** [comment]
For solving your requirements, you need to know some internals from the `ionic-logging-service`, since it is relying on [log4javascript](http://log4javascript.org/docs/manual.html#ajaxappender).

**enable/disable**

Modify the threshold of the appender:

```typescript
import * as log4javascript from "log4javascript";

ajaxAppender.setThreshold(log4javascript.Level.OFF);
```

**special information to each log statement**

This is currently not supported by `log4javascript`. I will keep it in mind for an upcoming release.

Currently you could add the device information as a query string to the url. And the evaluate it on the server side. However, for this you need to configure the appender by yourself, since the url cannot be changed later. That means, do not enable the ajaxAppender in the configuration, but call later:

```typescript
const ajaxAppender = new AjaxAppender({
  batchSize: 10,
  threshold: "WARN",
  timerInterval: 60,
  url: "http://server/path?device=" + this.device.uuid,
});
this.loggingService.getRootLogger().getInternalLogger().addAppender(ajaxAppender);
```

**batchSize and timerInterval**

I can understand your request, but unfortunately it is implemented in a different way by `log4javascript`:

> If batching is used in conjunction with timed sending of log messages, messages will still be sent in batches of size batchSize, regardless of how many log messages are queued by the time the timed sending is invoked. Incomplete batches will not be sent except when the page unloads, if sendAllOnUnload is set to true.

The property `sendAllOnUnload` is set to `true` in my implementation. So in most cases you should get the log message, e.g. when the app gets closed. But for sure this is not really reliable, so I set your request on my todo list.
